version: '3.7'

services:

  bitwarden:
    image: bitwardenrs/server:latest
    volumes:
      - bitwarden:/data
    environment:
      - VIRTUAL_HOST=${HOSTNAME}
      - LETSENCRYPT_HOST=${HOSTNAME}
      - WEBSOCKET_ENABLED='true'
      - SIGNUPS_ALLOWED='true'
    networks:
      - nginx-proxy


volumes:
  bitwarden:


networks: 
  nginx-proxy:
    external: true